### ISSUE TITLE
考虑切换数据库

### ISSUE THREAD

**Issue by rumtid** [lord63/wangyi_music_top100#20]
当前版本的数据库采用的是 Redis ，但就目前碰到的困难来看（#2 , #6 , #9 , #12 , #19），是否可以考虑切换到传统的关系型数据库？
@lord63

**Comment by lord63** [comment]
- #2 是个 idea，但是实现不实现目前还没有决定呢
- #6 不是已经有了么？
- #9 是前端的锅吧，跟数据库选择没有关系吧
- #12 是我的锅，我在试着做的更好
- #13 是爬取源的问题吧

目前其实和 redis 耦合地有点紧。但目前的问题感觉 redis 并不是一个大问题。你的看法呢？

**Comment by rumtid** [comment]
看上去目前切换数据库不是一个恰当的选择，性价比不高……
