### ISSUE TITLE
有网易云音乐评论的排行榜吗？

### ISSUE THREAD

**Issue by liguge** [lord63/wangyi_music_top100#23]

**Comment by lord63** [comment]
现在有评论数(一个歌单的评论数目)的排行，但是总体的评论数，并没有。

**Comment by liguge** [comment]
@lord63   有没有计划做一个啊~

**Comment by lord63** [comment]
@liguge 啊，目前并没有这样的计划呢。感觉量是挺大的。 Orz

**Comment by liguge** [comment]
@lord63 https://github.com/pengshiqi/NetEaseMusicCrawl

**Comment by lord63** [comment]
@liguge 多谢参考，不过没有计划  _(:3
